steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'GIT_HASH=$SHORT_SHA'
      - '-t'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:$SHORT_SHA'
      - '-t'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'simcash'
      - '--image'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:$SHORT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'

timeout: '1200s'
images:
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:$SHORT_SHA'
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simcash:latest'
