-- Migration 004: Add audit trail tables for Castro experiment
-- Created: 2025-12-09
-- Purpose: Store complete audit trails for LLM-driven policy optimization
--
-- This migration adds three tables to support Castro experiment audit functionality
-- as specified in: docs/plans/requests/castro-audit-trail-enhancement.md
--
-- Tables added:
-- 1. llm_interaction_log - Full LLM request/response cycle for debugging
-- 2. policy_diffs - Computed diffs and parameter snapshots for evolution tracking
-- 3. iteration_context - Simulation context provided to LLM for each optimization
--
-- Use cases:
-- - Debugging: Why did the LLM make this change? What context did it have?
-- - Research: How do policies evolve? What parameter patterns emerge?
-- - Compliance: Full audit trail of every decision for regulatory review
-- - Reproducibility: Re-run any iteration with exact same context
--
-- Schema is defined by Pydantic models in:
-- api/payment_simulator/ai_cash_mgmt/persistence/models.py
-- - LLMInteractionRecord
-- - PolicyDiffRecord
-- - IterationContextRecord
--
-- Note: Like previous migrations, this migration may be a no-op if the schema
-- was already initialized with the new models. The tables will be created
-- automatically by GameRepository.initialize_schema() from the Pydantic models.
--
-- In production workflow:
-- 1. Add the models to ai_cash_mgmt/persistence/models.py
-- 2. Add table creation to GameRepository.initialize_schema()
-- 3. Run initialize_schema() - tables and indexes are created automatically
--
-- This migration file serves as documentation of the schema change.

-- DO NOTHING
-- The audit tables will be created by GameRepository.initialize_schema().
-- Indexes will be created automatically.

-- Schema (for reference):

-- Table 1: LLM Interaction Log
-- CREATE TABLE llm_interaction_log (
--     interaction_id VARCHAR PRIMARY KEY,
--     game_id VARCHAR NOT NULL,
--     agent_id VARCHAR NOT NULL,
--     iteration_number INTEGER NOT NULL,
--     system_prompt TEXT NOT NULL,
--     user_prompt TEXT NOT NULL,
--     raw_response TEXT NOT NULL,
--     parsed_policy_json TEXT,
--     parsing_error TEXT,
--     llm_reasoning TEXT,
--     request_timestamp TIMESTAMP NOT NULL,
--     response_timestamp TIMESTAMP NOT NULL
-- );
-- CREATE INDEX idx_llm_log_game ON llm_interaction_log(game_id);
-- CREATE INDEX idx_llm_log_agent ON llm_interaction_log(game_id, agent_id);

-- Table 2: Policy Diffs
-- CREATE TABLE policy_diffs (
--     game_id VARCHAR NOT NULL,
--     agent_id VARCHAR NOT NULL,
--     iteration_number INTEGER NOT NULL,
--     diff_summary TEXT NOT NULL,
--     parameter_changes_json VARCHAR,
--     payment_tree_changed BOOLEAN NOT NULL DEFAULT FALSE,
--     collateral_tree_changed BOOLEAN NOT NULL DEFAULT FALSE,
--     parameters_snapshot_json VARCHAR NOT NULL,
--     PRIMARY KEY (game_id, agent_id, iteration_number)
-- );
-- CREATE INDEX idx_diffs_game ON policy_diffs(game_id);

-- Table 3: Iteration Context
-- CREATE TABLE iteration_context (
--     game_id VARCHAR NOT NULL,
--     agent_id VARCHAR NOT NULL,
--     iteration_number INTEGER NOT NULL,
--     monte_carlo_seeds VARCHAR NOT NULL,
--     num_samples INTEGER NOT NULL,
--     best_seed INTEGER NOT NULL,
--     worst_seed INTEGER NOT NULL,
--     best_seed_cost DOUBLE NOT NULL,
--     worst_seed_cost DOUBLE NOT NULL,
--     best_seed_verbose_output TEXT,
--     worst_seed_verbose_output TEXT,
--     cost_mean DOUBLE NOT NULL,
--     cost_std DOUBLE NOT NULL,
--     settlement_rate_mean DOUBLE NOT NULL,
--     PRIMARY KEY (game_id, agent_id, iteration_number)
-- );
-- CREATE INDEX idx_context_game ON iteration_context(game_id);

-- Example queries for analysis:

-- Policy Evolution Report:
-- SELECT
--     pi.iteration_number,
--     pd.diff_summary,
--     pi.old_cost,
--     pi.new_cost,
--     pi.was_accepted,
--     ic.best_seed,
--     ic.worst_seed
-- FROM policy_iterations pi
-- JOIN policy_diffs pd USING (game_id, agent_id, iteration_number)
-- JOIN iteration_context ic USING (game_id, agent_id, iteration_number)
-- WHERE pi.game_id = ? AND pi.agent_id = ?
-- ORDER BY pi.iteration_number;

-- Parameter Trajectory:
-- SELECT
--     iteration_number,
--     json_extract(parameters_snapshot_json, '$.urgency_threshold') as urgency_threshold,
--     json_extract(parameters_snapshot_json, '$.liquidity_buffer_factor') as liquidity_buffer
-- FROM policy_diffs
-- WHERE game_id = ? AND agent_id = ?
-- ORDER BY iteration_number;

-- Failed Parsing Analysis:
-- SELECT
--     game_id,
--     agent_id,
--     iteration_number,
--     parsing_error,
--     LEFT(raw_response, 500) as response_preview
-- FROM llm_interaction_log
-- WHERE parsing_error IS NOT NULL
-- ORDER BY request_timestamp DESC;
